FORMAT: 1A
HOST: https://api.tvarkaumiesta.lt/

# Tvarkau Miestą

API for Tvarkau Miestą apps. Manages problems reported by Lithuanian citizens.

# Group Authorization

Access to the API is granted using OAuth2. API requests must contain authorization header.

Example: `Authorization: Bearer accesstoken123`

Using OAuth2 client library is recommended to acquire access token.

Ruby example:

```ruby
require 'oauth2'

client = OAuth2::Client.new('android', nil, site: 'https://api.tvarkaumiesta.lt/oauth')
token = client.password.get_token('guest', 'guest')

puts token.token
```

## Access Token [/oauth/token]

+ Model (application/json)

        {
            "access_token": "7689bb55c6097159a5bca1a90b9aca2e6369c0c69f49929290459643feafb2ac",
            "token_type": "bearer",
            "expires_in": 7199,
            "refresh_token": "e7088e40a0d18143c0e09f805b501b08683ea81aa034eaa651123cacea329e75",
            "scope": "user",
            "created_at": 1513989843
        }

### Create an access token [POST]

#### Token refresh

If you already have an access token which has expired, you can use refresh token to get a new token.

Grant type: `refresh_token`

#### Guest login

Grant type: `password`

Pass `guest` value as username/password.

#### Web authorization

Grant type: `authorization_code`

First get authorization using `authorize` endpoint and pass it via `code` attribute. Also pass
`redirect_uri` which should be the same as passed to the `authorize` endpoint.

#### Login with email and password

Grant type: `password`

Email should be passed via `username` attribute.

#### Google / Facebook login

Grant type: `assertion`

Required Google/Facebook permissions: `email`

Acquire access token using
[Google](https://developers.google.com/identity/sign-in/)/[Facebook](https://developers.facebook.com/docs/facebook-login/)
SDK for your platform and pass it to the token endpoint via `assertion` attribute.

#### VIISP login - Elektroniniai valdžios vartai

Grant type: `assertion`

Acquire [VIISP access token](#reference/authorization/viisp-access-token)
and pass it to the token endpoint via `assertion` attribute.

+ Attributes
    + `client_id`: android (string, required) - Client app identifier. One of: *android*, *ios*, *web*.
    + `client_secret`: secret123 (string, optional) - Client secret. **Required for authorization_code grant type**.
    + `grant_type`: password (string, required) - OAuth2 grant type. One of: *password*, *assertion*, *authorization_code*, *refresh_token*.
    + `refresh_token`: token123 (string, optional) - Refresh token. **Required for refresh_token grant type**.
    + scope: user (string, optional) - Access scope.
    + username: gediminas@vilnius.lt (string, optional) - User's email address. **Required for password grant type**.
    + password: secret (string, optional) - User's password. **Required for password grant type**.
    + provider: google (string, optional) - Assertion provider. One of: *google*, *facebook*, *viisp*. **Required for assertion grant type**.
    + assertion: token123 (string, optional) - Google/Facebook/VIISP token. **Required for assertion grant type**.
    + code: code123 (string, optional) - Authorization code. **Required for authorization_code grant type**.
    + `redirect_uri`: https://tvarkaumiesta.lt/auth/callback (string, optional) - Redirect uri, must be the same as in authorize request. **Required for authorization_code grant type**.

+ Request Create a token using refresh token.

            {
                "grant_type": "refresh_token",
                "refresh_token": "token123",
            }

+ Response 200

  [Access Token][]

+ Request Create a guest user token.

            {
                "client_id": "android",
                "grant_type": "password",
                "scope": "user",
                "username": "guest",
                "password": "guest"
            }

+ Response 200

  [Access Token][]

+ Request Create a token using authorization code.

            {
                "client_id": "web",
                "client_secret": "secret123",
                "grant_type": "authorization_code",
                "scope": "user",
                "code": "authorizationcode123",
                "redirect_uri": "https://tvarkaumiesta.lt/auth/callback"
            }

+ Response 200

  [Access Token][]

+ Request Create a token using email/password.

            {
                "client_id": "android",
                "grant_type": "password",
                "scope": "user",
                "username": "gediminas@vilnius.lt",
                "password": "secret"
            }

+ Response 200

  [Access Token][]

+ Request Create a token using Facebook/Google/VIISP token.

            {
                "client_id": "android",
                "grant_type": "assertion",
                "scope": "user",
                "provider": "google",
                "assertion": "token123"
            }

+ Response 200

  [Access Token][]

## Authorization Code [/oauth/authorize{?client_id,response_type,redirect_uri}]

### Get an authorization code [GET]

Client will be redirected to the authorization web page. After picking authorization method and
successfully authorizing she will be redirected back to the `redirect_url` with authorization
`code`. Authorization code should be exchanged to the access token using `token` endpoint.

+ Parameters
    + client_id: web (string, required) - Client app identifier.
    + response_type: code (string, required) - Response type.
    + redirect_uri: https://tvarkaumiesta.lt/auth/callback (string, required) - Redirect uri.

+ Response 302

## VIISP Access Token [/auth/viisp/new{?redirect_uri}]

After successful authorization user will be redirected to the `redirect_uri` with the access token.
VIISP access token should be exchanged to the API access token using OAuth2 assertion grant.

Android/iOS apps can use custom url scheme to handle return to the application with the token.

### Start authorization [GET]

+ Parameters
    + redirect_uri: lt.tvarkauvilniu://viisp/callback (string, required) - URI where user should be redirected after successful authorization.

+ Response 200 (text/html)

        <html>
            <body>
                A web page automatically redirecting to VIISP authorization system.
            </body>
        </html>

# Group Cities

## Cities Collection [/cities]

### List Cities [GET]

+ Response 200 (application/json)

        {
            "cities": [
                {
                    "id": 1,
                    ...
                },
                {
                    "id": 2,
                    ...
                },
            ]
        }

# Group Users

## Current User [/me]

### Get current user profile [GET]

+ Response 200 (application/json)

        {
            "user": {
                "id": 1,
                "email": "user1@vilnius.lt",
                "created_at": "2017-12-23T13:35:46.000Z"
            }
        }

# Group Reports

## Report [/reports/{report_id}]

+ Parameters
    + report_id: 1 (number, required) - The id of the Report

+ Model (application/json)

        {
            "report": {
                "id": 1,
                "ref_no": null,
                "report_type_id": 1,
                "lat": "9.99",
                "lng": "9.99",
                "user_id": 2,
                "status_id": 1,
                "description": "Description",
                "answer": null,
                "license_plate_no": "ABC123",
                "registered_at": "2017-02-24T22:17:25.000Z",
                "completed_at": null,
                "report_photos": [
                    {
                        "id": 1,
                        "uuid": "some-uuid",
                        "photo_url": "https://url/photo.jpg",
                        "photo_thumb_url": "https://url/photo_thumb.jpg"
                    }
                ]
            }
        }

### Retrieve a Report [GET]

+ Response 200

  [Report][]

## Reports Collection [/reports{?type,status,page,per_page}]

### List Reports [GET]

+ Parameters
    + type: 1 (number, optional) - Report type id
    + status: 1 (number, optional) - Report status id
    + page: 2 (number, optional) - Page number
    + per_page: 20 (number, optional) - Returned entries limit

+ Response 200 (application/json)

        {
            "reports": [
                {
                    "id": 1,
                    ...
                },
                {
                    "id": 2,
                    ...
                },
            ]
        }

### Create a New Report [POST]

+ Request

  [Report][]

+ Response 201

  [Report][]

# Group Report Types

## Report Types Collection [/report_types]

### List Report Types [GET]

Get report types list for current user city.

+ Response 200 (application/json)

        {
            "report_types": [
                {
                    "id": 1,
                    ...
                },
                {
                    "id": 2,
                    ...
                },
            ]
        }

# Group Report Statuses

## Report Statuses Collection [/report_statuses]

### List Report Statuses [GET]

+ Response 200 (application/json)

        {
            "report_statuses": [
                {
                    "id": 1,
                    ...
                },
                {
                    "id": 2,
                    ...
                },
            ]
        }
        
# Group Report Photos

## Report Photos Collection [/report_photos]

### Create a New Report Photo [POST]

+ Attributes
    + report_photo (object)
        + file: filedata (string) - Uploaded file (multipart)

+ Response 201

        {
            "report_photo": {
                "id": 1,
                "uuid": "some-uuid",
                "photo_url": "https://url/photo.jpg",
                "photo_thumb_url": "https://url/photo_thumb.jpg"
            }
        }
