FORMAT: 1A
HOST: https://api.tvarkaumiesta.lt/

# Tvarkau Miestą
API for Tvarkau Miestą apps. Manages problems reported by Lithuanian citizens.

# Authorization

## Token [/oauth/token]

+ Model (application/json)

        {
            "access_token": "7689bb55c6097159a5bca1a90b9aca2e6369c0c69f49929290459643feafb2ac",
            "token_type": "bearer",
            "expires_in": 7199,
            "scope": "user",
            "created_at": 1513989843
        }

### Get a new token [POST]

+ Attributes
    + client_id: android (string, required) - Client app identifier. One of: *android*, *ios*, *web*.
    + grant_type: assertion (string, required) - OAuth2 grant type. One of: *assertion*, *password*.
    + scope: user (string, optional) - Access scope.
    + provider: google (string, optional) - Assertion provider. One of: *google*, *facebook*, *viisp*. **Required for assertion grant type.**
    + assertion: token123 (string, optional) - Google/Facebook/VIISP token. **Required for assertion grant type.**
    + username: gediminas@vilnius.lt (string, optional) - User's email address. **Required for password grand type.**
    + password: secret (string, optional) - User's password. **Required for password grand type.**

+ Response 200

  [Token][]

# Reports

## Report [/api/reports/{report_id}]

+ Parameters
    + report_id (required, number, `1`) - The id of the Report

+ Model (application/json)

        {
            "id": 1,
            "ref_no": null,
            "report_type_id": 1,
            "lat": "9.99",
            "lng": "9.99",
            "user_id": 2,
            "status_id": 1,
            "description": "Description",
            "answer": null,
            "license_plate_no": "ABC123",
            "registered_at": "2017-02-24T22:17:25.000Z",
            "completed_at": null
        }

### Retrieve a Report [GET]

+ Response 200

  [Report][]

## Reports Collection [/api/reports?{?type,status,limit,offset}]

### List Reports [GET]

+ Parameters
    + type (optional, number, `1`) ... Report type id
    + status (optional, number, `1`) ... Report status id
    + limit (optional, number, `20`) ... Returned entries limit
    + offset (optional, number, `0`) ... List offset

+ Response 200 (application/json)

        {
            "entries": [
                {
                    "id": 1,
                    ...
                },
                {
                    "id": 2,
                    ...
                },
            ]
        }

### Create a New Report [POST]

+ Request

  [Report][]

+ Response 201

  [Report][]

