package lt.vilnius.tvarkau.issue

enum IssueType {
    TRAFFIC,
    ENERGY_ENGINEERING_NETWORKS,
    STREET_LIGHTING,
    STREET_MAINTENANCE,
    ANIMAL_RULES_VIOLATION,
    OUTDOORS_ADVERTISING_VIOLATION,
    CEMETERY_MAINTENANCE,
    WASTE_MANAGEMENT,
    BUILDING_ADMINISTRATION,
    BRIDGES_VIADUCTS_TUNNELS_TRESTLES_MAINTENANCE,
    NOISE_PREVENTION_VIOLATION,
    CLEANLINESS_VIOLATION,
    PUBLIC_TRANSPORTATION,
    ENVIRONMENTAL_CARE,
    PARKING_VIOLATION,
    CONSTRUCTION_CARE,
    HOMELESS_ANIMALS,
    BICYCLE_ROUTES
}